trigger:
- main

strategy:
 matrix:
  linux:
    operatingSystem: 'ubuntu-latest'
  windows:
    operatingSystem: 'windows-latest'
pool:
  vmImage: $(operatingSystem)

steps:
- script: echo running on $(operatingSystem)
  displayName: 'Run a one-line script'

- script: |
  #   echo Add other tasks to build, test, and deploy your project.
  #   echo See https://aka.ms/yaml
  # displayName: 'Run a multi-line script'
