trigger:
- main

# strategy:
#  matrix:
#   linux:
#     operatingSystem: 'ubuntu-latest'
#   windows:
#     operatingSystem: 'windows-latest'
pool:
  vmImage: 'ubuntu-latest'
stages:
 - stage: Build
   jobs:
    - job: BuildJob
      steps: 
       - bash: echo "Do the build"
#  - stage: DevDeploy
#    jobs:
#     - job: DevDeploy
#       steps: 
#        - bash: echo "Do the DevDeploy"
 - stage: DevDeploy
   jobs:
   - deployment: DevDeployjob
     environment: Dev
     strategy: 
      runOnce:
        deploy:
         steps:
          - script: echo Deploy to Dev
 - stage: QADeploy
   jobs:
    - deployment: QADeploy
      environment: QA
      strategy: 
       runOnce:
        deploy:
         steps:
          - script: echo Deploy to QA



# - script: |
#   #   echo Add other tasks to build, test, and deploy your project.
#   #   echo See https://aka.ms/yaml
#   # displayName: 'Run a multi-line script'
